### ISSUE TITLE
source: command not found

### ISSUE THREAD

**Issue by amirulabu** [inishchith/autoenv#171]
I have done a directory and added the virtualenv as usual. 
```
virtualenv -p /usr/bin/python3.5 env
```
then i get this on my terminal 
```
ruler@X230:~$ cd workspace/django-test/
“source: command not found
```

**Comment by Gnouc** [comment]
@amirulabu which shell do you use?

**Comment by inishchith** [comment]
[ I know this is too late ]

@amirulabu Please feel free to reopen in case you still face the error :)
